# Generated by Django 4.2.27 on 2025-12-22 03:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255, verbose_name='搜索关键词')),
                ('email', models.EmailField(max_length=254, verbose_name='通知邮箱')),
                ('status', models.CharField(choices=[('PENDING', '排队中'), ('RUNNING', '正在爬取'), ('SUCCESS', '检索成功'), ('FAILURE', '检索失败')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('disk_type', models.CharField(help_text='如：阿里云盘', max_length=50)),
                ('url', models.TextField()),
                ('site_source', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='search.searchtask')),
            ],
        ),
    ]
