# Generated by Django 4.2.27 on 2025-12-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resourceresult',
            table='resource_results',
        ),
        migrations.AlterModelTable(
            name='searchtask',
            table='search_tasks',
        ),
    ]
