# Generated by Django 4.2.27 on 2025-12-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtask',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
